
services:
  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DB_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${DB_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    container_name: django_backend
    build: ./backend
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    container_name: react_frontend
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host"]

    volumes:
      - ./frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules

volumes:
  postgres_data:
  node_modules: