# Generated by Django 5.1.5 on 2025-04-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hours_per_month', models.IntegerField()),
                ('hours_per_day', models.IntegerField()),
                ('free_days', models.DateField()),
                ('shift_preference', models.CharField(max_length=100)),
                ('special_shift_preferences', models.CharField(max_length=100)),
                ('special_hours_preferences', models.CharField(max_length=100)),
            ],
        ),
    ]
